### ISSUE TITLE
[Bug] Issues with login with v0.1.5-beta

### ISSUE THREAD

**Issue by bigboban** [dvejsada/HA-RohlikCZ#27]
Previous non-HACS version worked fine. Last HACS 0.1.5-beta - login failed.

```
2025-04-30 07:44:54.134 ERROR (MainThread) [custom_components.rohlikcz.config_flow] Unknown exception
Traceback (most recent call last):
  File "/config/custom_components/rohlikcz/config_flow.py", line 49, in async_step_user
    info, data = await validate_input(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rohlikcz/config_flow.py", line 24, in validate_input
    reply = await api.get_data()
            ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rohlikcz/rohlik_api.py", line 62, in get_data
    self._address_id = result["login"].get("data", {}).get("address", {}).get("id", None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2025-04-30 07:44:54.136 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=custom_components.rohlikcz.config_flow, message=['Unknown exception'], level=ERROR, source=('custom_components/rohlikcz/config_flow.py', 49), timestamp=1745991894.1341732, exception=Traceback (most recent call last):
  File "/config/custom_components/rohlikcz/config_flow.py", line 49, in async_step_user
    info, data = await validate_input(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rohlikcz/config_flow.py", line 24, in validate_input
    reply = await api.get_data()
            ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rohlikcz/rohlik_api.py", line 62, in get_data
    self._address_id = result["login"].get("data", {}).get("address", {}).get("id", None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get', count=1, first_occurred=1745991894.1341732>

```

**Comment by dvejsada** [comment]
I can see the issue. To get around before I fix it, install previous version from HACS, configure the integration and than update to the latest.

**Comment by dvejsada** [comment]
@bigboban unfortunately, I am not able to reproduce the error, setting up the integration works fine for me on v0.1.5 as well. Most likely cause seems to be that you have **no home delivery address set with your account** and this is a why trying to load address id fails. Is it correct?

**Comment by budisek** [comment]
I have same issue with login with last version

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/06514c5a-ef52-4254-9764-fff94e2f2e5d" />

**Comment by dvejsada** [comment]
@bigboban @budisek In order for me to determine the root cause, can you kindly do the following:

1. Go to rohlik.cz website
2. Logout
3. Right click -> Inspect -> Network
4. Login to your account
5. Find request to login endpoint
6. Copy the response here (after removing your personal data from the response)

Thanks!

**Comment by budisek** [comment]
Is this right?

```
Request URL:
https://www.rohlik.cz/services/frontend-service/login
Request Method:
POST
Status Code:
200 OK
Remote Address:
104.18.171.******
Referrer Policy:
no-referrer-when-downgrade
access-control-allow-origin:
*
alt-svc:
h3=":443"; ma=86400
cf-cache-status:
DYNAMIC
cf-ray:
93a980d53b20a5dc-PRG
content-encoding:
gzip
content-type:
application/json
date:
Sun, 04 May 2025 16:51:30 GMT
expires:
Thu, 01 Jan 1970 00:00:00 GMT
feature-policy:
autoplay 'none';camera 'none';microphone 'none';geolocation 'self'
priority:
u=1,i
referrer-policy:
no-referrer-when-downgrade
server:
cloudflare
server-timing:
cfExtPri
set-cookie:
PHPSESSION=kkP0zMBX7Hfuee2tfKDkY1qfNosXvrkj; Path=/; Domain=.rohlik.cz; Expires=Tue, 3 Jun 2025 16:51:30 GMT; Max-Age=2592000; Secure; HttpOnly
set-cookie:
JSESSIONID=node0qrqk5kp4uj1ke1jip9s98hqa32628387.node0; Path=/; HttpOnly
strict-transport-security:
max-age=31536000; includeSubDomains; preload
vary:
Accept-Encoding
vary:
Origin
vary:
Access-Control-Request-Method
vary:
Access-Control-Request-Headers
via:
1.1 google
x-content-type-options:
nosniff
x-dns-prefetch-control:
off
x-frame-options:
SAMEORIGIN
x-xss-protection:
1; mode=block
:authority:
www.rohlik.cz
:method:
POST
:path:
/services/frontend-service/login
:scheme:
https
accept:
*/*
accept-encoding:
gzip, deflate, br, zstd
accept-language:
cs,pl;q=0.9,sk;q=0.8,de;q=0.7
baggage:
sentry-environment=production,sentry-release=2025-04-29_14-26-37-524,sentry-public_key=a04769022c7841959445930b1f8dc5df,sentry-trace_id=9e4ccd27549e4d1e85174c6b1ec9222a,sentry-sample_rate=0.2,sentry-transaction=%2F,sentry-sampled=false
content-length:
66
content-type:
application/json
cookie:
language=cs-CZ; NEXT_LOCALE=cs-CZ; lastVisit=1746377420007; currentVisit=1746377420007; __cfruid=cbea227e29275b3abc0e56baaf12e20504d6935a-1746377420; _cfuvid=a8ZlZiVJdB34rpSz6vAJiMCwu82Lg7vZbCBm_xppkM0-1746377420115-0.0.1.1-604800000; cf_clearance=J_Oi26p8gyM1JKHJTQiq3CLsVi2355CoJFFWlyrD49g-1746377422-1.2.1.1-7Vu1dFNYKoO_WqAx2OmU06Ig2yEIqOAUAf1bUb5dgeU8j00ta_xzs8I._OfeF82iLSBRcjlnT8z5UleGJX9KosztE9Qyn0UyRWSdSNXo5saGfHomUtQETcMmf0.b86plxO17OF2ObqShLobakHpzSFXD1cnDQqtfRvZYYFEu5PEojHGaQTEt3MO1KgSXnsM22fihaKQHIgIsVlLrNQrkoX_Cj5zJH8f.6fiwXkNJo.YSxA8nM8J6v6dXhYqrauPxzufIjINMeaC26uCKZPEIUlwUK1Fqm5InOrGOlieJHRFnfPocymC0xouLu1TCXm1IT08gMsoaRNIhmL0Il0nxFwsh4Lvd_4fFSNkbysZHeTM; userId=4140071; PHPSESSION=OTVGWlS9UOSRHkTDunbrJxNsGcbhVdxL; tutorialDelivery=true; JSESSIONID=node0139pp47twjwj0d58wz9fyaemm32628104.node0; _dd_s=aid=507080f1-26b6-486c-a1d0-b891f686fd03&rum=0&expire=1746378404282
origin:
https://www.rohlik.cz
priority:
u=1, i
referer:
https://www.rohlik.cz/
sec-ch-ua:
"Not(A:Brand";v="99", "Opera";v="119", "Chromium";v="133"
sec-ch-ua-mobile:
?0
sec-ch-ua-platform:
"Windows"
sec-fetch-dest:
empty
sec-fetch-mode:
cors
sec-fetch-site:
same-origin
sentry-trace:
9e4ccd27549e4d1e85174c6b1ec9222a-8c07af841cd9c8b6-0
user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 OPR/119.0.0.0 (Edition developer)
x-b3-spanid:
ctbsa2wsqyzq1z35
x-b3-traceid:
ctbsa2wsqyzq1z35
x-origin:
WEB
x-rohlikid:
dfea4186d4744c2fb34e95e1a8e9e85242eb54e7
```

**Comment by budisek** [comment]
```
{
    "status": 200,
    "messages": [],
    "data": {
        "status": 0,
        "fbLoginUrl": null,
        "uniqsid": null,
        "user": {
            "id": 4140071,
            "email": "*************",
            "name": "************",
            "phone": "+420*********",
            "salutation": "******",
            "remainingOrdersWithoutLimit": *,
            "remainingFreeExpress": *,
            "demoUser": false,
            "parentsClub": false,
            "star": false,
            "reusablePackaging": true,
            "mobileAppUsage": false,
            "newBuyer": false,
            "sex": "SEX_UNKNOWN",
            "credits": 0.00,
            "premium": {
                "active": true,
                "premiumMembershipType": "YEARLY",
                "premiumType": "PAID",
                "wasActive": true,
                "premiumInvoiceLink": "*****",
                "recurrentPaymentDate": "2026-04-16",
                "type": "YEARLY_PREMIUM",
                "failedPayment": false,
                "lastActivePremium": null,
                "showExpiredMembership": false,
                "premiumLimits": {
                    "unlimited": false,
                    "ordersWithoutPriceLimit": {
                        "remaining": 2,
                        "total": 4,
                        "enabled": true
                    },
                    "freeExpressLimit": {
                        "remaining": 4,
                        "total": null,
                        "enabled": false
                    }
                },
                "remainingDays": 375,
                "premiumProfileEnabled": true,
                "firstTimePremium": false,
                "newPremiumLandingPageEnabled": true,
                "freeTrial": false,
                "xtraEnabled": true,
                "startDate": "16. 4. 2025",
                "endDate": "16. 5. 2026"
            },
            "deliveryTypeSelected": "COURIER",
            "timeSlotReservation": {
                "active": false,
                "enabledForUser": true,
                "newForPremium": false
            }
        },
        "address": {
            "id": ********,
            "fullAddress": "**********",
            "street": "*********",
            "postalCode": "******",
            "city": "***********",
            "isDeliveredTo": true,
            "latitude": **************,
            "longitude": *********,
            "stores": [
                {
                    "storeId": 8793
                }
            ],
            "flatDetails": {
                "entrance": null,
                "floor": null,
                "door": null,
                "block": null,
                "apartment": null,
                "staircase": null,
                "intercom": null,
                "additionalInfo": null
            }
        },
        "zoneId": null,
        "availableStores": [
            {
                "storeId": 8793
            }
        ],
        "features": [
            "FEATURE_PREMIUM",
            "FEATURE_SENIORS",
            "FEATURE_DELIVERY_POINT",
            "FEATURE_PARENTS_CLUB",
            "FEATURE_WATCHDOG",
            "FEATURE_MEAL_TICKETS",
            "FEATURE_ADDITIVES_DATABASE",
            "FEATURE_SEASONAL_OPENING_HOURS",
            "FEATURE_IMPORT_RECIPE",
            "FEATURE_CUSTOM_RECIPE",
            "FEATURE_ONLINE_VOUCHERS",
            "FEATURE_LANGUAGE_SWITCH",
            "FEATURE_CHEF",
            "FEATURE_CLAIMS",
            "FEATURE_CHAT",
            "FEATURE_FB_LOGIN",
            "FEATURE_RETURNABLE_BOTTLES",
            "FEATURE_REVERSE_GEOCODING",
            "FEATURE_GOOGLE_LOGIN",
            "FEATURE_PREMIUM_FREE_EXPRESS",
            "FEATURE_PREMIUM_ORDERS_WITHOUT_PRICE_LIMIT",
            "FEATURE_APPLE_LOGIN",
            "FEATURE_AI_ASSISTANT_CHAT",
            "FEATURE_AI_ASSISTANT_CHAT_STREAMING",
            "FEATURE_AI_ASSISTANT_ATTACHMENTS",
            "FEATURE_PERSONALIZATION_CONSENT",
            "FEATURE_CRITEO",
            "FEATURE_XTRA"
        ],
        "deliveryPoint": null,
        "segment": "PREMIUM",
        "personalizationConsent": false,
        "newUserCreated": false,
        "isAuthenticated": true,
        "store": {
            "storeId": 8793
        },
        "isAdmin": false
    }
}
```

**Comment by dvejsada** [comment]
@bigboban @budisek I am not able to locate the core issue (I believe it is error when fetching login data that is not properly caught), but I have made some changes to error handling and address_id retrieval, hopefully this will remove the issue or at least provide some additional information. Try updating to 0.1.6 and let me know.

**Comment by budisek** [comment]
It does work in 2.0 version. Now I can login successfully. Thanks 👍

**Comment by dvejsada** [comment]
> I have the same problem with new version 2.0
> 
> ```
> 2025-05-10 08:05:14.997 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *** for rohlikcz
> Traceback (most recent call last):
>   File "/config/custom_components/rohlikcz/rohlik_api.py", line 122, in login
>     self._address_id = login_response.get("data", {}).get("address", {}).get("id", None)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/rohlikcz/__init__.py", line 22, in async_setup_entry
>     await account.async_update()
>   File "/config/custom_components/rohlikcz/hub.py", line 43, in async_update
>     self.data = await self._rohlik_api.get_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/rohlikcz/rohlik_api.py", line 155, in get_data
>     result["login"] = await self.login(session)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/rohlikcz/rohlik_api.py", line 124, in login
>     raise AddressNotSetError(f"Address is not set in the account: {err}")
> custom_components.rohlikcz.errors.AddressNotSetError: Address is not set in the account: 'NoneType' object has no attribute 'get'
> 2025-05-10 08:05:16.817 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140071638557664] Error handling message: Unknown error (unknown_error) Vojta from 192.168.100.1 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2025.3 (io.robbie.HomeAssistant; build:2025.1205; iOS 18.5.0) Mobile/HomeAssistant, like Safari)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
>     await func(hass, connection, msg)
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 542, in handle_manifest_list
>     raise int_or_exc
> homeassistant.loader.IntegrationNotFound: Integrat
> ```

I understand this happens after the restart of the Home Assistant? If you try to manually reload the integration after the initial fail, does it fail again?

**Comment by budisek** [comment]
Yes. This is after reload. 

![Image](https://github.com/user-attachments/assets/ca1780a8-9fb6-48b1-ba85-678eab28f34d)

**Comment by dvejsada** [comment]
Closing for now, will reopen if the issue persists.
